version: '3.7'

services:
  backend:
    #    name of container
    container_name: verbo_app_backend
    #    name of image
    image: backend-app-image
    build: ./
    restart: always
    ports:
      #    HOST:CONTAINER
      - 8081:8080
    depends_on:
      - pg_db
    environment:
      DB_PORT: 5432
      DB_HOST: verbo_app_database
      DB_USER: postgres
      DB_PASS: 123

  pg_db:
    container_name: verbo_app_database
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: VERBO_DB
    ports:
      #    HOST:CONTAINER
      - "5400:5432"

