spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/VERBO_DB
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
  flyway:
    locations: classpath:db/migration/dev, classpath:db/migration/test
  sql:
    init:
      platform: postgres
