spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/VERBO_DB
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
  flyway:
    locations: classpath:db/migration/dev, classpath:db/migration/test
  sql:
    init:
      platform: postgres
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/verbo_keys.p12
    key-store-password: Defender13
    key-alias: Verbo
    enabled: true



#на всякий случай
#server:
#  ssl:
#    key-store-type: JKS
#    key-store:  classpath:keystore/verbo_keys.jks
#    key-store-password: Defender13
#    key-alias: Verbo
#    enabled: true

